version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres@localhost
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
